### ISSUE TITLE
MySQL/MariaDB requirement for datainjection?

### ISSUE THREAD

**Issue by thenamelessthing** [pluginsGLPI/datainjection#166] opened 2019-09-23 18:32 UTC
Hi, I try to install datainjection 2.5.2 for my GLPI 9.2.1

and I obtain this error:

 Erreur durant l'éxecution de la requête : CREATE TABLE IF NOT EXISTS glpi_plugin_datainjection_models ( id int(11) NOT NULL auto_increment, name varchar(255) NOT NULL, comment text NULL, date_mod datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, date_creation datetime DEFAULT NULL, filetype varchar(255) NOT NULL default 'csv', itemtype varchar(255) NOT NULL default '', entities_id int(11) NOT NULL default '0', behavior_add tinyint(1) NOT NULL default '1', behavior_update tinyint(1) NOT NULL default '0', can_add_dropdown tinyint(1) NOT NULL default '0', can_overwrite_if_not_empty int(1) NOT NULL default '1', is_private tinyint(1) NOT NULL default '1', is_recursive tinyint(1) NOT NULL default '0', perform_network_connection tinyint(1) NOT NULL default '0', users_id int(11) NOT NULL, date_format varchar(11) NOT NULL default 'yyyy-mm-dd', float_format tinyint( 1 ) NOT NULL DEFAULT '0', port_unicity tinyint( 1 ) NOT NULL DEFAULT '0', step int( 11 ) NOT NULL DEFAULT '0', PRIMARY KEY (id) ) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_unicode_ci - L'erreur est Invalid default value for 'date_mod'

actually I'm under mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

Which version is requird to work?

Thanks you

**Comment by stonebuzz** [comment] 2020-01-28 10:54
Hi @thenamelessthing 

please update glpi and datainjection to latest version.

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-28 10:54 UTC
Labels: need feedback
