### ISSUE TITLE
Define Request and Incident models in itil Category

### ISSUE THREAD

**Issue by tiagomf1** [pluginsGLPI/datainjection#176] opened 2020-01-13 12:48 UTC
Define Request and Incident models in itil Category not working in Data injection for  GLPI 9.3

**Comment by tiagomf1** [comment] 2020-01-13 14:28
Profiler shows the id 366 of "testesCat" model, the script finds the correct id of the model but set 1 for the Insert in glpi_itilcategories


Used insert: 
" INSERT INTO `glpi_itilcategories` (`name`, `itilcategories_id`, `entities_id`, `comment`, `**tickettemplates_id_demand**`, `**tickettemplates_id_incident**`, `is_request`, `is_incident`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('TESTES', '0', '0', 'Categoria de teste', '**1**', '**1**', '1', '1', '1', 'TESTES', '2020-01-13 10:39:50', '2020-01-13 10:39:50') " 






Complete Query Profiler:
/usr/sbin/mysqld, Version: 5.6.42 (MySQL Community Server (GPL)). started with:
Tcp port: 3306  Unix socket: /var/run/mysqld/mysqld.sock

Time                 Id Command    Argument
200113 10:39:50	37358 Connect	glpi@garcezqas.bahiana.intranet on glpi
		37358 Query	SET NAMES utf8
		37358 Query	SET SESSION sql_mode = ''
		37358 Query	SELECT * FROM `glpi_configs` WHERE `glpi_configs`.`id` = '1' LIMIT 1
		37358 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37358 Query	SHOW COLUMNS FROM `glpi_configs`
		37358 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_db')
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37358 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_trans')
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winupdates%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_proxysettings%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winusers%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_teamviewers%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_osinstalls%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_networkshares%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_runningprocesses%'
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_services%'
		37358 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'surveyticket'
		37358 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '4' LIMIT 1
		37358 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'actualtime'
		37358 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '5' LIMIT 1
		37358 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_actualtime_configs%'
		37358 Query	SELECT * FROM `glpi_plugin_actualtime_configs` WHERE `glpi_plugin_actualtime_configs`.`id` = '1' LIMIT 1
		37358 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection'
		37358 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '10' LIMIT 1
		37358 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection'
		37358 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '10' LIMIT 1
		37358 Query	SELECT * FROM `glpi_plugin_datainjection_models` WHERE `glpi_plugin_datainjection_models`.`id` = '2' LIMIT 1
		37358 Query	SELECT * FROM `glpi_plugin_datainjection_models` WHERE `glpi_plugin_datainjection_models`.`id` = '2' LIMIT 1
		37358 Query	(SELECT `itemtype`
                 FROM `glpi_plugin_datainjection_models`
                 WHERE `id` = '2')
                UNION (SELECT DISTINCT `itemtype`
                       FROM `glpi_plugin_datainjection_mappings`
                       WHERE `models_id` = '2')
                UNION (SELECT DISTINCT `itemtype`
                       FROM `glpi_plugin_datainjection_infos`
                       WHERE `models_id` = '2')
		37358 Query	SELECT *
                FROM `glpi_plugin_datainjection_infos`
                WHERE `models_id` = '2'
                ORDER BY `itemtype` ASC
		37358 Query	SHOW COLUMNS FROM `glpi_itilcategories`
		37358 Query	SELECT `id`
                FROM `glpi_plugin_datainjection_modelcsvs`
                WHERE `models_id` = '2'
		37358 Query	SELECT * FROM `glpi_plugin_datainjection_modelcsvs` WHERE `glpi_plugin_datainjection_modelcsvs`.`id` = '2' LIMIT 1
		37358 Query	SELECT `id`
                FROM `glpi_plugin_datainjection_modelcsvs`
                WHERE `models_id` = '2'
		37358 Query	SELECT * FROM `glpi_plugin_datainjection_modelcsvs` WHERE `glpi_plugin_datainjection_modelcsvs`.`id` = '2' LIMIT 1
		37358 Query	SELECT *
              FROM `glpi_plugin_datainjection_mappings`
              WHERE `models_id` = '2'
              ORDER BY `rank` ASC
		37358 Quit	
		37359 Connect	glpi@garcezqas.bahiana.intranet on glpi
		37359 Query	SET NAMES utf8
		37359 Query	SET SESSION sql_mode = ''
		37359 Query	SELECT * FROM `glpi_configs` WHERE `glpi_configs`.`id` = '1' LIMIT 1
		37359 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37359 Query	SHOW COLUMNS FROM `glpi_configs`
		37359 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_db')
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37359 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_trans')
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winupdates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_proxysettings%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winusers%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_teamviewers%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_osinstalls%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_networkshares%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_runningprocesses%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_services%'
		37359 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'surveyticket'
		37359 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '4' LIMIT 1
		37359 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'actualtime'
		37359 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '5' LIMIT 1
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_actualtime_configs%'
		37359 Query	SELECT * FROM `glpi_plugin_actualtime_configs` WHERE `glpi_plugin_actualtime_configs`.`id` = '1' LIMIT 1
		37359 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection'
		37359 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '10' LIMIT 1
		37359 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection'
		37359 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '10' LIMIT 1
		37359 Query	SELECT *
              FROM `glpi_plugin_datainjection_mappings`
              WHERE `models_id` = '2'
              ORDER BY `rank` ASC
		37359 Query	SELECT `value`,
                        COUNT(*) AS counter
                 FROM `glpi_plugin_datainjection_mappings`
                 WHERE `models_id` = '2'
                       AND `value` NOT IN ('none')
                 GROUP BY `value`
                 HAVING `counter` > 1
		37359 Query	SELECT *
                FROM `glpi_plugin_datainjection_infos`
                WHERE `models_id` = '2'
                ORDER BY `itemtype` ASC
		37359 Query	SELECT `id`
                FROM `glpi_plugin_datainjection_modelcsvs`
                WHERE `models_id` = '2'
		37359 Query	SELECT * FROM `glpi_plugin_datainjection_modelcsvs` WHERE `glpi_plugin_datainjection_modelcsvs`.`id` = '2' LIMIT 1
		37359 Query	SELECT `value`,
                        COUNT(*) AS counter
                 FROM `glpi_plugin_datainjection_mappings`
                 WHERE `models_id` = '2'
                       AND `value` NOT IN ('none')
                 GROUP BY `value`
                 HAVING `counter` > 1
		37359 Query	SHOW COLUMNS FROM `glpi_itilcategories`
		37359 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'ocsinventoryng'
		37359 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '3' LIMIT 1
		37359 Query	SHOW COLUMNS FROM `glpi_tickettemplates`
		37359 Query	SELECT  `id` FROM `glpi_tickettemplates` WHERE `name` = 'testesCat' AND `glpi_tickettemplates`.`entities_id` = '0' LIMIT 1
		37359 Query	SELECT * FROM `glpi_tickettemplatepredefinedfields` WHERE `tickettemplates_id` IS NULL
		37359 Query	SELECT * FROM `glpi_tickettemplatemandatoryfields` WHERE `tickettemplates_id` IS NULL
		37359 Query	SELECT * FROM `glpi_tickettemplatehiddenfields` WHERE `tickettemplates_id` IS NULL
		37359 Query	SELECT * FROM `glpi_tickettemplatepredefinedfields` WHERE `tickettemplates_id` = '366'
		37359 Query	SELECT * FROM `glpi_tickettemplatemandatoryfields` WHERE `tickettemplates_id` = '366'
		37359 Query	SELECT * FROM `glpi_tickettemplatehiddenfields` WHERE `tickettemplates_id` = '366'
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_incident` IS NULL
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_demand` IS NULL
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_incident` = '366'
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_demand` = '366'
		37359 Query	SELECT * FROM `glpi_tickettemplates` WHERE `glpi_tickettemplates`.`id` = '366' LIMIT 1
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `id` FROM `glpi_tickettemplates` WHERE `name` = 'testesCat' AND `glpi_tickettemplates`.`entities_id` = '0' LIMIT 1
		37359 Query	SELECT * FROM `glpi_tickettemplatepredefinedfields` WHERE `tickettemplates_id` IS NULL
		37359 Query	SELECT * FROM `glpi_tickettemplatemandatoryfields` WHERE `tickettemplates_id` IS NULL
		37359 Query	SELECT * FROM `glpi_tickettemplatehiddenfields` WHERE `tickettemplates_id` IS NULL
		37359 Query	SELECT * FROM `glpi_tickettemplatepredefinedfields` WHERE `tickettemplates_id` = '366'
		37359 Query	SELECT * FROM `glpi_tickettemplatemandatoryfields` WHERE `tickettemplates_id` = '366'
		37359 Query	SELECT * FROM `glpi_tickettemplatehiddenfields` WHERE `tickettemplates_id` = '366'
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_incident` IS NULL
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_demand` IS NULL
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_incident` = '366'
		37359 Query	SELECT * FROM `glpi_itilcategories` WHERE `tickettemplates_id_demand` = '366'
		37359 Query	SELECT * FROM `glpi_tickettemplates` WHERE `glpi_tickettemplates`.`id` = '366' LIMIT 1
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_tickettemplates%'
		
		
		37359 Query	SELECT *
                    FROM `glpi_itilcategories` WHERE 1  AND ( `glpi_itilcategories`.`entities_id` = '0'  )   AND `comment`='Categoria de teste' AND `completename`='TESTES' AND `tickettemplates_id_demand`='1' AND `tickettemplates_id_incident`='1'
					
					
		37359 Query	SELECT `id`
                   FROM `glpi_itilcategories`
                   WHERE `name` = 'TESTES'
                         AND `itilcategories_id` = '0' AND  ( `glpi_itilcategories`.`entities_id` = '0'  )
						 
						 
		37359 Query	INSERT INTO `glpi_itilcategories` (`name`, `itilcategories_id`, `entities_id`, `comment`, `tickettemplates_id_demand`, `tickettemplates_id_incident`, `is_request`, `is_incident`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('TESTES', '0', '0', 'Categoria de teste', '1', '1', '1', '1', '1', 'TESTES', '2020-01-13 10:39:50', '2020-01-13 10:39:50')
		37359 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_itilcategories%'
		37359 Query	SELECT `id`, `ancestors_cache`, `itilcategories_id` FROM `glpi_itilcategories` WHERE `id` IN ('451')
		37359 Query	UPDATE `glpi_itilcategories` SET `ancestors_cache` = '[]' WHERE `id` = '451'
		37359 Query	SELECT * FROM `glpi_users` WHERE `id` = '2'
		37359 Query	INSERT INTO `glpi_logs` (`items_id`, `itemtype`, `itemtype_link`, `linked_action`, `user_name`, `date_mod`, `id_search_option`, `old_value`, `new_value`) VALUES ('451', 'ITILCategory', '0', '20', 'GLPI - Admin (2)', '2020-01-13 10:39:50', '0', '', '')
		37359 Quit	
		37360 Connect	glpi@garcezqas.bahiana.intranet on glpi
		37360 Query	SET NAMES utf8
		37360 Query	SET SESSION sql_mode = ''
		37360 Query	SELECT * FROM `glpi_configs` WHERE `glpi_configs`.`id` = '1' LIMIT 1
		37360 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37360 Query	SHOW COLUMNS FROM `glpi_configs`
		37360 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_db')
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_configs%'
		37360 Query	SELECT * FROM `glpi_configs` WHERE `context` = 'core' AND `name` IN ('cache_trans')
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winupdates%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_proxysettings%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_winusers%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_teamviewers%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_osinstalls%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_networkshares%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_runningprocesses%'
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_ocsinventoryng_services%'
		37360 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'surveyticket'
		37360 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '4' LIMIT 1
		37360 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'actualtime'
		37360 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '5' LIMIT 1
		37360 Query	SELECT  `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE '%glpi_plugin_actualtime_configs%'
		37360 Query	SELECT * FROM `glpi_plugin_actualtime_configs` WHERE `glpi_plugin_actualtime_configs`.`id` = '1' LIMIT 1
		37360 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection'
		37360 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '10' LIMIT 1
		37360 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection'
		37360 Query	SELECT * FROM `glpi_plugins` WHERE `glpi_plugins`.`id` = '10' LIMIT 1
		37360 Query	SELECT  `id` FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'pdf'
		37360 Quit	
200113 10:39:56	37357 Query	SET GLOBAL general_log='OFF'

**Comment by stonebuzz** [comment] 2020-01-28 13:21
Hi @tiagomf1 

already fixed on latest version, please update glpi and datainjetion.

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-28 13:21 UTC
