### ISSUE TITLE
entities import

### ISSUE THREAD

**Issue by Bigjoke007** [pluginsGLPI/datainjection#105] opened 2018-07-26 11:05 UTC
Place to import entities?
When I import entities they go to root by default could I change that? and import them to a child entities?

**Comment by loicbenoit** [comment] 2018-08-22 15:34
### What I understand
1. You imported entities successfully in GLPI from a CSV using plugin DataInjection.
2. They got imported under root instead of another entity.

### Suggestion 1
Try selecting the target entity as current context in upper right corner of your screen before importing data.  It will set the default entity to use when importing. Make sure your import file doesn't contain field "entities_id".

### Suggestion 2
Try adding field "entities_id" in the import file. For each CSV record, specify the ID of the parent entity.

### Warning
Backup your server before trying these suggestions. I did not test them.

**Comment by Bigjoke007** [comment] 2018-08-29 16:59
Hi,

I tried both without succes.

Entities are still imported in root

By the way this doesn"t work anymore on 2.6.1  since there is entry to match "Entity Name" in correspodance menu

**Comment by Bigjoke007** [comment] 2018-10-18 09:51
@loicbenoit 
Any Update?

Regards

**Comment by OlinuxX** [comment] 2018-11-30 14:04
I second this request.
I have thousands of child entities to add to one of our entities and unfortunately they are inserted under the root one.

I tried @loicbenoit 's suggestion 1 without success before seeing this thread.
I did not bother with suggestion 2 because it failed for @Bigjoke007 

I also tried to move the entities to the child entity that I wanted, but it also did not work.

Can someone provide a solution ?

I'm trying to set this up for work but it could be a no go if there's none (we are using GLPI for years trying now to go to the next level with it).

Regards

**Comment by OlinuxX** [comment] 2018-11-30 15:41
2 other informations :
- it's not possible to move entities under another one, and even if it was possible, mass actions stop at 1000 objects
- GLPI 9.1.2

**Comment by loicbenoit** [comment] 2018-12-01 03:01
Importing entities into table glpi_entities and moving entities under a new parent entity are two different things.

DataInjection may help with importing entities. It can only help to move them by mean of updating entity records, which seems to implies preparing everything outside of GLPI. If you have thousands of entities, you'll probably have to write a script to generate the import file.

If you have to write a script anyway, you might as well add the functionnality to GLPI (assuming it doesn't already exists, since you didn't find it). This would have to be done as an enhancement request to the main GLPI project. It's not in the scope of plugin DataInjection.

I'll try to find time next week to test importing entities into table glpi_entities using DataInjection. 

Else, a direct import using a tool like PhpMyAdmin might also work, although you'd have to know what you're doing: You're import file must properly relate entities together as data would be imported raw directly into table glpi_entities. **Never attempt this without a proper backup of everything.**

**Comment by loicbenoit** [comment] 2018-12-09 19:01
Thanks that helps with understanding your situation and trying to reproduce it. I couldn't find time last week, but will try again this week.

**Comment by loicbenoit** [comment] 2019-01-07 17:43
### What I did
1. While under root entity, I created a DataInjection model for itemtype "entity" with options: "entity = root", "recursive = True", "create rows = true", "update rows = true".
2. The data mapping file contained a single field: "complete name", marked as a link field.
3. In my CSV file, I prefixed my new entity with the complete name of an existing entity, such as:
root > my_existing_entity > my_new_entity

### Actual result is the expected result
The new entity is imported under "root > my_existing_entity" as "root > my_existing_entity > my_new_entity".

However, it only worked when selecting "root" as the entity everywhere.

### Question
Can you correctly import a single child entity using this method?

**Comment by loicbenoit** [comment] 2019-01-07 18:03
I was able to import an entity as a child to another entity using the method above, provided that I did not include the "root > " part of the complete name while under "root".

In your data file, use this "my_existing_entity > my_new_entity" instead of this "root > my_existing_entity > my_new_entity"

Please test this method with 1 or 2 rows and let me know how it turns out.

**Comment by OlinuxX** [comment] 2019-01-27 15:09
This solution works flawlessly, many thanks.
Sorry for not getting back to you earlier, I had no time to test this before.

Unfortunately, it raised 2 others difficulties, that I will have to create issues for :
- line breaks in addresses are imported as "n" characters (similar to issue #138 ). I tried to change the file format between Windows and Linux and other tests without any success 
- I didn't manage to update the address field even though the model has lines creation, lines update and existing fields update set to **yes**.

Anyways, thank you.

**Comment by felag** [comment] 2020-06-19 08:14
Hello, just to let you know that I have opened an issue, because I have the same following problem. It is #206.

> I didn't manage to update the address field even though the model has lines creation, lines update and existing fields update set to **yes**.

**Comment by cedric-anne** [comment] 2020-10-21 13:28
Hi all,

#217 should handle this issue. Could you test ?

Regards

**Closed** 2024-02-22 08:20 UTC
