### ISSUE TITLE
Use of deleted librairy of GLPI core

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/datainjection#159] opened 2019-08-06 10:46 UTC
![image](https://user-images.githubusercontent.com/12936722/62533911-16221800-b848-11e9-92f3-d87eaf31dd1b.png)

This error is for datainjection 2.4.2 but still present in master version

**Comment by stonebuzz** [comment] 2020-01-28 14:21
Hi @yllen 

This issue hasn't evolved in a long time and is fixed by #160 

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-28 14:21 UTC
Labels: bug
